-- Create meter_reading table
CREATE TABLE IF NOT EXISTS meter_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT REFERENCES contract(id) ON DELETE CASCADE,
    room_id BIGINT REFERENCES room(id) ON DELETE CASCADE, -- Optional but helpful for direct access
    prev_water FLOAT NOT NULL DEFAULT 0,
    current_water FLOAT NOT NULL DEFAULT 0,
    prev_electricity FLOAT NOT NULL DEFAULT 0,
    current_electricity FLOAT NOT NULL DEFAULT 0,
    reading_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add Reference to Room if needed (Invoice usually links Contract)
-- But for Dashboard, linking Contract is sufficient if Contract links to Room.
-- Added room_id for easier querying if Contract is archived.

-- RLS Policies (Optional - enable if RLS is on)
ALTER TABLE meter_reading ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON meter_reading FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON meter_reading FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');
CREATE POLICY "Enable update for authenticated users only" ON meter_reading FOR UPDATE USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
CREATE POLICY "Enable delete for authenticated users only" ON meter_reading FOR DELETE USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
