-- Migration: 009_add_maintenance_parts
-- Purpose: Adds a table to store requested parts from mechanics that wait for manager approval.

CREATE TABLE IF NOT EXISTS public.maintenance_parts (
    id bigint generated by default as identity primary key,
    maintenance_id bigint references public.maintenance_request(id) on delete cascade not null,
    part_name text not null,
    price numeric(10,2) not null,
    status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.maintenance_parts ENABLE ROW LEVEL SECURITY;

-- Create policy for all operations (for simplicity in internal app)
CREATE POLICY "Enable all operations for authenticated users on maintenance_parts"
ON public.maintenance_parts
FOR ALL USING (true) WITH CHECK (true);
