-- Start a transaction
BEGIN;

-- 1. Create a mapping of old IDs to new sequential IDs
CREATE TEMP TABLE branch_id_mapping AS
SELECT 
    id AS old_id,
    ROW_NUMBER() OVER (ORDER BY branches_name) AS new_id
FROM branch;

-- 2. Temporarily change the identity column to "BY DEFAULT" so we can update it
ALTER TABLE branch ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 3. Disable Foreign Key checks by setting replication role to replica
SET session_replication_role = 'replica'; 

-- 4. Update 'building' table
UPDATE building
SET branch_id = map.new_id
FROM branch_id_mapping map
WHERE building.branch_id = map.old_id;

-- 5. Update 'users' table
UPDATE users
SET branch_id = map.new_id
FROM branch_id_mapping map
WHERE users.branch_id = map.old_id;

-- 6. Update 'branch' table (Now allowed because of step 2)
UPDATE branch
SET id = map.new_id
FROM branch_id_mapping map
WHERE branch.id = map.old_id;

-- 7. Update user usernames
UPDATE users
SET username = REGEXP_REPLACE(username, '_' || map.old_id || '$', '_' || map.new_id)
FROM branch_id_mapping map
WHERE users.username LIKE '%_' || map.old_id;

-- 8. Reset the ID sequence to the max ID + 1
DO $$
DECLARE
    max_id INT;
BEGIN
    SELECT MAX(id) + 1 INTO max_id FROM branch;
    EXECUTE 'ALTER TABLE branch ALTER COLUMN id RESTART WITH ' || max_id;
END $$;

-- 9. Re-enable Foreign Key checks
SET session_replication_role = 'origin';

-- 10. Restore identity column to "ALWAYS" (Optional - strictly restores original schema)
ALTER TABLE branch ALTER COLUMN id SET GENERATED ALWAYS;

COMMIT;

-- Verify
SELECT * FROM branch ORDER BY id;
